### ISSUE TITLE
BigNumber parsing error

### ISSUE THREAD

**Issue by dwalintukan** [bodhiproject/bodhi-graphql#40]
I made a bet through the UI (1.2345678 qtum). Here is the log:
```
{
    "result": [
        {
            "blockHash": "9de98d99ed370da9cc2dd4563c86dd9861b1876189ea86a3e304067114ef78f1",
            "blockNumber": 57040,
            "transactionHash": "fd0a69f44d0fbe7dec057adc39fe69bfbb029c13b2eba271dd8b4f4179541e62",
            "transactionIndex": 2,
            "from": "17e7888aa7412a735f336d2f6d784caefabb6fa3",
            "to": "71a0e61292f5a6b8d6c493d6696a587c660e3cb5",
            "cumulativeGasUsed": 137993,
            "gasUsed": 137993,
            "contractAddress": "71a0e61292f5a6b8d6c493d6696a587c660e3cb5",
            "log": [
                {
                    "address": "71a0e61292f5a6b8d6c493d6696a587c660e3cb5",
                    "topics": [
                        "0f6520c85c2e282b6c54e14e5b424ca7eafc89615f05f2d35f3c1f9110e9df03",
                        "00000000000000000000000071a0e61292f5a6b8d6c493d6696a587c660e3cb5",
                        "00000000000000000000000017e7888aa7412a735f336d2f6d784caefabb6fa3"
                    ],
                    "data": "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000075bcd0c"
                }
            ]
        }
    ]
}
```

And when checking graph output, I received this. I believe it is related to my bet as it is not showing up in DB:
```
(node:6474) UnhandledPromiseRejectionWarning: Error: Number can only safely store up to 53 bits
    at assert (/Users/deric/coding/bodhi-graphql/node_modules/bn.js/lib/bn.js:6:21)
    at BN.toNumber (/Users/deric/coding/bodhi-graphql/node_modules/bn.js/lib/bn.js:506:7)
    at CentralizedOracle.decode (/Users/deric/coding/bodhi-graphql/src/sync/models/centralizedOracle.js:29:60)
    at new CentralizedOracle (/Users/deric/coding/bodhi-graphql/src/sync/models/centralizedOracle.js:12:12)
    at Promise (/Users/deric/coding/bodhi-graphql/src/sync/index.js:145:35)
    at new Promise (<anonymous>)
    at _.forEachRight (/Users/deric/coding/bodhi-graphql/src/sync/index.js:144:34)
    at arrayEachRight (/Users/deric/coding/bodhi-graphql/node_modules/lodash/lodash.js:557:11)
    at Function.forEachRight (/Users/deric/coding/bodhi-graphql/node_modules/lodash/lodash.js:9384:14)
    at _.forEach (/Users/deric/coding/bodhi-graphql/src/sync/index.js:142:11)
```

**Comment by dwalintukan** [comment]
Looks this is appearing in `topic.js`, `centralizedOracle.js` models. It's trying to call `BN.toNumber()` but breaking the Int type in js.

**Comment by dwalintukan** [comment]
Looks like this due to a block number that wasn't returning right. One of them was returning as this `<BN: deda0000000000000000000000>`. And was causing the above error. I put all the `constructor > translate()` calls inside the try catch block and it fixed it. It was an unhandled promise error.

https://github.com/bodhiproject/bodhi-graphql/pull/42
