### ISSUE TITLE
Syncing seems to hang/stop sometimes

### ISSUE THREAD

**Issue by dwalintukan** [bodhiproject/bodhi-graphql#41]
The synchronizer seems to stop sometimes. Not sure if this is related to the `UnhandledPromiseRejectionWarning` shown here (related #40) or not. But it stopped syncing at 57037. Current block now is 57049.

```
searchlog TopicCreated
57036 - 57037: Retrieved 3 entries from TopicCreated
(node:6474) UnhandledPromiseRejectionWarning: Error: Number can only safely store up to 53 bits
    at assert (/Users/deric/coding/bodhi-graphql/node_modules/bn.js/lib/bn.js:6:21)
    at BN.toNumber (/Users/deric/coding/bodhi-graphql/node_modules/bn.js/lib/bn.js:506:7)
    at Topic.decode (/Users/deric/coding/bodhi-graphql/src/sync/models/topic.js:27:60)
    at new Topic (/Users/deric/coding/bodhi-graphql/src/sync/models/topic.js:12:12)
    at Promise (/Users/deric/coding/bodhi-graphql/src/sync/index.js:103:27)
    at new Promise (<anonymous>)
    at _.forEachRight (/Users/deric/coding/bodhi-graphql/src/sync/index.js:102:33)
    at arrayEachRight (/Users/deric/coding/bodhi-graphql/node_modules/lodash/lodash.js:557:11)
    at Function.forEachRight (/Users/deric/coding/bodhi-graphql/node_modules/lodash/lodash.js:9384:14)
    at _.forEach (/Users/deric/coding/bodhi-graphql/src/sync/index.js:100:11)
(node:6474) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6474) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
searchlog CentralizedOracleCreated
57036 - 57037: Retrieved 3 entries from CentralizedOracleCreated
(node:6474) UnhandledPromiseRejectionWarning: Error: Number can only safely store up to 53 bits
    at assert (/Users/deric/coding/bodhi-graphql/node_modules/bn.js/lib/bn.js:6:21)
    at BN.toNumber (/Users/deric/coding/bodhi-graphql/node_modules/bn.js/lib/bn.js:506:7)
    at CentralizedOracle.decode (/Users/deric/coding/bodhi-graphql/src/sync/models/centralizedOracle.js:29:60)
    at new CentralizedOracle (/Users/deric/coding/bodhi-graphql/src/sync/models/centralizedOracle.js:12:12)
    at Promise (/Users/deric/coding/bodhi-graphql/src/sync/index.js:145:35)
    at new Promise (<anonymous>)
    at _.forEachRight (/Users/deric/coding/bodhi-graphql/src/sync/index.js:144:34)
    at arrayEachRight (/Users/deric/coding/bodhi-graphql/node_modules/lodash/lodash.js:557:11)
    at Function.forEachRight (/Users/deric/coding/bodhi-graphql/node_modules/lodash/lodash.js:9384:14)
    at _.forEach (/Users/deric/coding/bodhi-graphql/src/sync/index.js:142:11)
(node:6474) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
searchlog OracleResultVoted
57036 - 57037: Retrieved 3 entries from OracleResultVoted
searchlog FinalResultSet
57036 - 57037: Retrieved 3 entries from FinalResultSet
searchlog DecentralizedOracleCreated
57036 - 57037: Retrieved 3 entries from DecentralizedOracleCreated
searchlog OracleResultSet
57036 - 57037: Retrieved 3 entries from OracleResultSet
```

**Comment by dwalintukan** [comment]
I think this is related to the error in the log. I started up synchronizer again and its stalling at the current block.
